### PR TITLE
Added instructions to add the service unit files.

### PR DESCRIPTION
**Pull request by VMTrooper**
Instructions on how to handle the service unit files were missing.

### CODE REVIEW

**Comment by pires** [comment]
@kelseyhightower care to merge this?

**Comment by VMTrooper** [comment]
Kelsey modified the walk through so that the unit files are automatically deployed.  So, this pull request can be ignored.

**Comment by pires** [comment]
Where did he do that? Another repo?

**Comment by VMTrooper** [comment]
Yes.  The updated workflows are found in the official Google Kubernetes repo:

https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides/coreos/cloud-configs

**Comment by pires** [comment]
Tks

**Pull request closed without merging**
